[package]
name = "sdk-lookup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
colored = "2.0.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
